export const cards_zombiaki_json = [
  {
    "id": 1,
    "amount": 1,
    "name": "MIŚ",
    "type": "overlay",
    "description": "Połóż Misia na wybranego Zombiaka (z wyjątkiem Psa i Kota). Miś porusza się razem z Zombiakiem. W twojej turze możesz zmniejszyć siłę Misia o 1, aby grający ludźmi odrzucił 2 karty, a nie 1 w najbliższej fazie Odrzucenia. Miś może być atakowany tak jak Zombiak. Grający ludźmi może atakować Zombiaka lub Misia - jeśli Miś otrzyma więcej ran niż ma aktualnie siły, to pozostałe rany otrzymuje Zombiak. Jeśli Zombiak zginie, to Miś ginie razem z nim.",
    "flavor": "Misio chce zombiaczka.",
    "hp": 4,
    "max_hp": 4,
    "special": true,
    "race": "zombiaki"
  },
  {
    "id": 2,
    "amount": 2,
    "name": "KLIK",
    "type": "other",
    "description": "Możesz zagrać Klik w turze Ludzi jako odpowiedź na Strzał, Serię lub Snajpera. Klik niweluje działanie jednej takiej karty.",
    "flavor": "Johnowi Rambo się to nie zdarzało.",
    "special": true,
    "race": "zombiaki"
  },
  {
    "id": 3,
    "amount": 1,
    "name": "WACEK",
    "type": "zombiak",
    "description": "Na początku twojej tury Zombiak przesuwa się o 1 pole do przodu.",
    "flavor": "Taki sobie, na trzy plus.",
    "hp": 3,
    "max_hp": 3,
    "race": "zombiaki"
  },
  {
    "id": 4,
    "amount": 1,
    "name": "KOT",
    "type": "zombiak",
    "description": "Kot porusza się przed Zombiakami o 1 lub 2 pola w dowolnym kierunku (nie po skosie). Może wejść na pole zajęte przez innego Zombiaka i odwrotnie. Jeśli Kot i Zombiak będą na jednym polu, to Kot pierwszy otrzymuje obrażenia. Trafiony i niezabity Kot nie cofa się. Jeśli Kot otrzyma więcej ran niż potrzeba do jego zabicia, to pozostałe rany otrzymuje Zombiak na tym samym polu. Po dotarciu Kota do Barykady ludzi nic się nie dzieje. Na Kota nie można zagrywać kart z talii zombich.",
    "flavor": "Wlazł kotek na grobek",
    "hp": 2,
    "max_hp": 2,
    "special": true,
    "race": "zombiaki"
  },
  {
    "id": 5,
    "amount": 1,
    "name": "KRYSTYNKA",
    "type": "zombiak",
    "description": "Na początku twojej tury przesuń Zombiaka o 1 pole do przodu. Dodatkowo, jeśli w tej samej przecznicy co ona znajduje się inny Zombiak, to nie wolno zagrywać przeciwko niej: Strzałów, Serii, Snajpera, Miotacza, Cegły.",
    "flavor": "Silikon nie gnije.",
    "hp": 3,
    "max_hp": 3,
    "special": true,
    "race": "zombiaki"
  },
  {
    "id": 6,
    "amount": 1,
    "name": "ZENEK",
    "type": "zombiak",
    "description": "Na początku twojej tury Zombiak przesuwa się o 1 pole do przodu.",
    "flavor": "Za życia też go nikt nie lubił.",
    "hp": 3,
    "max_hp": 3,
    "race": "zombiaki"
  },
  {
    "id": 7,
    "amount": 1,
    "name": "ANDRZEJ",
    "type": "zombiak",
    "description": "Na początku twojej tury Zombiak przesuwa się o 1 pole do przodu.",
    "flavor": "Powróżyć Ci?",
    "hp": 3,
    "max_hp": 3,
    "race": "zombiaki"
  },
  {
    "id": 8,
    "amount": 1,
    "name": "KILOF",
    "type": "other",
    "description": "Odrzuć na Śmietnik dowolną, leżącą na planszy kartę planszy z talii ludzi (z wyjątkiem Dziury).",
    "flavor": "Niestety to mi przeszkadza.",
    "special": true,
    "race": "zombiaki"
  },
  {
    "id": 9,
    "amount": 3,
    "name": "CZŁOWIEK",
    "type": "overlay",
    "description": "Połóż Człowieka na dowolnym Zombiaku. Człowiek absorbuje wszystkie obrażenia wynikające z jednej karty zadane temu Zombiakowi, po czym ginie.",
    "flavor": "Do kumpla będziesz strzelał?",
    "special": true,
    "race": "zombiaki"
  },
  {
    "id": 10,
    "amount": 1,
    "name": "WIADRO",
    "type": "other",
    "description": "Nie możesz tej karty odrzucić. Musisz ją zagrać jako pierwszą kartę w turze, w której ją dociągnąłeś – wybierz dowolnego Zombiaka i porusz go o 1 pole do tyłu. Jeśli żaden Zombiak nie jest w stanie poruszyć się do tyłu, to wybrany przez ciebie Zombiak otrzymuje 1 ranę.",
    "flavor": "Hełm z ograniczoną widocznością.",
    "special": true,
    "race": "zombiaki"
  },
  {
    "id": 11,
    "amount": 1,
    "name": "STEFAN",
    "type": "zombiak",
    "description": "Na początku twojej tury Zombiak przesuwa się o 1 pole do przodu.",
    "flavor": "Kwiaty we włosach potargał wiatr...",
    "hp": 4,
    "max_hp": 4,
    "race": "zombiaki"
  },
  {
    "id": 12,
    "amount": 1,
    "name": "MARIUSZ",
    "type": "zombiak",
    "description": "Na początku twojej tury Zombiak przesuwa się o 1 pole do przodu.",
    "flavor": "Wszystkie Mariusze to fajne chłopaki",
    "hp": 4,
    "max_hp": 4,
    "race": "zombiaki"
  },
  {
    "id": 13,
    "amount": 2,
    "name": "TERROR",
    "type": "other",
    "description": "Grający ludźmi w następnej trze może zagrać tylko jedną kartę",
    "flavor": "Ty! W garniturku! Skądżeś się tu wziął?",
    "special": true,
    "race": "zombiaki"
  },
  {
    "id": 14,
    "amount": 1,
    "name": "PIES",
    "type": "zombiak",
    "description": "Pies porusza się przed Zombiakami od 1 do 3 pól w dowolnym kierunku (nie po skosie). Po dotarciu Psa do Barykady ludzi nic się nie dzieje. Na Psa nie można zagrywać kart z talii zombich.",
    "flavor": "Najlepszy przyjaciel Zombiaka.",
    "hp": 1,
    "max_hp": 1,
    "special": true,
    "race": "zombiaki"
  },
  {
    "id": 15,
    "amount": 1,
    "name": "MŁODY",
    "type": "zombiak",
    "description": "Na początku twojej tury przesuń Zombiaka o 1 pole do przodu. Siła Młodego jest tym większa, im bliżej Barykady się znajduje. Siła 2 (podstawowo), Siła 3 (na IV przecznicy), Siła 4 (na III przecznicy), Siła 5 (na II przecznicy), Siła 6 (na I przecznicy).",
    "flavor": "Jaki Zombiak, taki syn.",
    "hp": 2,
    "max_hp": 4,
    "special": true,
    "race": "zombiaki"
  },
  {
    "id": 16,
    "amount": 1,
    "name": "PAZURY",
    "type": "overlay",
    "description": "ZAgraj Pazury na wybranego Zombiaka. Pazury zwiększają siłę Zombiaka o 1.",
    "flavor": "Może małe manicure?",
    "special": true,
    "race": "zombiaki"
  },
  {
    "id": 17,
    "amount": 1,
    "name": "KAZIMIERZ",
    "type": "zombiak",
    "description": "Na początku twojej tury Zombiak przesuwa się o 1 pole do przodu.",
    "flavor": "Atrakcyjny to on nie jest.",
    "hp": 3,
    "max_hp": 3,
    "race": "zombiaki"
  },
  {
    "id": 18,
    "amount": 1,
    "name": "KRZYSZTOF",
    "type": "zombiak",
    "description": "Na początku twojej tury Zombiak przesuwa się o 1 pole do przodu.",
    "flavor": "Mięso armatnie. Raczej tatar niż schabowe.",
    "hp": 2,
    "max_hp": 2,
    "race": "zombiaki"
  },
  {
    "id": 19,
    "amount": 1,
    "name": "BOSS",
    "type": "overlay",
    "description": "Połóż Bossa na dowolnym Zombiaku. Boss może wydać 3 rozkazy (1 na turę) pozwalające na dodatkowy ruch innego Zombiaka. Rozkazów słuchają Zombiaki o sile 3 i mniejszej. Gdy Zombiak-Boss zginie, wszystkie Zombiaki cofają się o 1 pole.",
    "flavor": "Teraz ja tu rządzę.",
    "special": true,
    "race": "zombiaki"
  },
  {
    "id": 20,
    "amount": 1,
    "name": "MARIAN",
    "type": "zombiak",
    "description": "Na początku twojej tury Zombiak przesuwa się o 1 pole do przodu.",
    "flavor": "Marian zaprasza do tańca.",
    "hp": 4,
    "max_hp": 4,
    "race": "zombiaki"
  },
  {
    "id": 21,
    "amount": 1,
    "name": "CZESIEK",
    "type": "zombiak",
    "description": "Na początku twojej tury Zombiak przesuwa się o 1 pole do przodu.",
    "flavor": "Taki mały władca much.",
    "hp": 2,
    "max_hp": 2,
    "race": "zombiaki"
  },
  {
    "id": 22,
    "amount": 1,
    "name": "SYJAMCZYK",
    "type": "zombiak",
    "description": "Na początku twojej tury przesuń Zombiaka o 1 pole do przodu. Dodatkowo, kiedy Syjamczyk zginie, zamienia się w 2 Zombiaki o sile 1 (odwróć jego kartę w miejscu, w którym zginął, a drugą połóż na wolnym polu sąsiadującym z nim z boku lub z tyłu).",
    "flavor": "Co dwie głowy, to nie jedna.",
    "hp": 2,
    "max_hp": 2,
    "special": true,
    "race": "zombiaki"
  },
  {
    "id": 23,
    "amount": 1,
    "name": "GALARETA",
    "type": "zombiak",
    "description": "Na początku twojej tury przesuń Zombiaka o 1 pole do przodu. Dodatkowo, kiedy Galareta zostanie zabity, pozostawia w swoim miejscu żeton galarety. Pierwszy Zombiak (z wyjątkiem Psa i Kota), który wejdzie na pole z tym żetonem, zabiera go – dodaje mu on +2 siły.",
    "flavor": "Żelatyna jest dobra na kości.",
    "hp": 3,
    "max_hp": 3,
    "special": true,
    "race": "zombiaki"
  },
  {
    "id": 24,
    "amount": 1,
    "name": "GŁÓD",
    "type": "other",
    "description": "Przesuń dowolnego Zombiaka o 1 pole do przodu o ile jest to możliwe",
    "flavor": "Bierz go!",
    "special": true,
    "race": "zombiaki"
  },
  {
    "id": 25,
    "amount": 1,
    "name": "ARKADIUSZ",
    "type": "zombiak",
    "description": "Na początku twojej tury Zombiak przesuwa się o 1 pole do przodu.",
    "flavor": "Jak się bawiłeś na mojej stypie?",
    "hp": 3,
    "max_hp": 3,
    "race": "zombiaki"
  },
  {
    "id": 26,
    "amount": 1,
    "name": "MIETEK",
    "type": "zombiak",
    "description": "Na początku twojej tury Zombiak przesuwa się o 1 pole do przodu.",
    "flavor": "Setka na wzmocnienie Mietka.",
    "hp": 3,
    "max_hp": 3,
    "race": "zombiaki"
  },
  {
    "id": 27,
    "amount": 2,
    "name": "MASA",
    "type": "other",
    "description": "Przesuń dowolnego Zombiaka na sąsiednie pole zajmowane przez innego Zombiaka (również jeśli obaj są zasieciowani). Obaj traktowani są jak nowy Zombiak o sile równej sumie ich sił. Jeśli zmasujesz Zombiaka z cechą specjalną, to przestaje ona obowiązywać.",
    "flavor": "Kupy nikt nie rusza.",
    "special": true,
    "race": "zombiaki"
  },
  {
    "id": 28,
    "amount": 1,
    "name": "MIĘSO",
    "type": "other",
    "description": "Wybierz jedną z kart przeciwnika leżących na Barykadzie i odrzuć ją na Śmietnik",
    "flavor": "Łap pan teściową!",
    "special": true,
    "race": "zombiaki"
  },
  {
    "id": 29,
    "amount": 1,
    "name": "PAPU",
    "type": "other",
    "description": "Usuń do 2 znaczników ran z wybranego Zombiaka.",
    "flavor": "Dietę zaczynam od jutra.",
    "special": true,
    "race": "zombiaki"
  },
  {
    "id": 30,
    "amount": 1,
    "name": "KOŃ TROJAŃSKI",
    "type": "zombiak",
    "description": "Na początku twojej tury przesuń Zombiaka o 1 pole do przodu. Dodatkowo, kiedy Koń Trojański zginie, zamienia się w 3 Zombiaki o sile 1 (odwróć jego kartę w miejscu, w którym zginął, a pozostałe 2 połóż na wolnych polach sąsiadujących z nim z boku i/lub z tyłu).",
    "flavor": "Zwykła zabawka, zwykła zabawka...",
    "hp": 2,
    "max_hp": 2,
    "special": true,
    "race": "zombiaki"
  },
  {
    "id": 31,
    "amount": 1,
    "name": "SPADAJ",
    "type": "other",
    "description": "Zamień miejscami dwa Zombiaki sąsiadujące ze sobą (nie po skosie), o ile żaden z nich nie jest splątany siecią. Karta nie działa na Psa ani Kota.",
    "flavor": "Miejsce dla mądrzejszego!",
    "special": true,
    "race": "zombiaki"
  },
  {
    "id": 32,
    "amount": 1,
    "name": "UGRYZIENIE",
    "type": "other",
    "description": "Zamień Człowieka w nowego Zombiaka o sile 1, umieść go na sąsiednim polu (z tyłu lub z boku). Jeżeli wszystkie sąsiednie pola są zablokowane, Ugryzienie nie może zostać zagrane.",
    "flavor": "Pajęczyca.",
    "special": true,
    "race": "zombiaki"
  },
  {
    "id": 33,
    "amount": 1,
    "name": "IWAN",
    "type": "zombiak",
    "description": "Na początku twojej tury Zombiak przesuwa się o 1 pole do przodu.",
    "flavor": "IWAN: chłopak na piątkę.",
    "hp": 5,
    "max_hp": 5,
    "race": "zombiaki"
  },
  {
    "id": 34,
    "amount": 1,
    "name": "KULOODPORNY",
    "type": "zombiak",
    "description": "Na początku twojej tury przesuń Zombiaka o 1 pole do przodu. Dodatkowo, Kuloodporny ignoruje całkowicie efekty Strzałów.",
    "flavor": "Twardy jak dębowa trumna.",
    "hp": 3,
    "max_hp": 3,
    "special": true,
    "race": "zombiaki"
  }
]
