
export const cards_ludzie_json = [
    {
        "id": 1,
        "amount": 1,
        "name": "STAĆ",
        "type": "other",
        "instruction": "Na początku swojej najbliższej tury Zombiaki nie wykonują przymusowego ruchu.",
        "description": "Na początku swojej najbliższej tury Zombiaki nie wykonują przymusowego ruchu.",
        "flavor": "Dokumenty poproszę!",
        "race": "ludzie"
    },
    {
        "id": 2,
        "amount": 1,
        "dmg": 2,
        "piercing": true,
        "name": "KRÓTKA SERIA",
        "type": "shot",
        "instruction": "Seria. Krótka seria trafia najbliższego Zombiaka na wybranym torze i zadaje mu 2 rany. Jeśli pierwsza rana zabiła Zombiaka, drugą otrzymuje kolejny Zombiak stojący na tym torze. Dodatkowo, trafiony i nie zabity Zombiak cofa się o 1 pole, o ile jest to możliwe. Uwaga: Człowiek absorbuje wszystkie pociski wystrzelone w Serii.",
        "description": "Krótka seria trafia najbliższego Zombiaka na torze i zadaje 2 rany. Jeśli pierwsza rana zabiła Zombniaka, drugą otrzymuje kolejny Zombiak na torze.Trafienie cofa Zombiaka o 1 pole.Człowiek absorbuje wszystkie pociski Serii.",
        "flavor": "Łykaj kule, aumarlaku!",
        "blockable": true,
        "race": "ludzie",
        "board": true,
    },
    {
        "id": 3,
        "amount": 1,
        "dmg": 1,
        "name": "220V",
        "type": "AOE",
        "instruction": "Zagraj 220V na dowolny tor. Urwany drut wysokiego napięcia zadaje 1 ranę każdemu Zombiakowi znajdującemu się na tym torze.",
        "description": "Zagraj 200V na dowolny tor. Urwany drut wysokiego napięcia zadaje 1 ranę każdemu Zombiakowi znajdującemu się na tym torze.",
        "flavor": "Chyba cię pokopało?",
        "race": "ludzie",
        "board": true,
    },
    {
        "id": 4,
        "amount": 7,
        "dmg": 1,
        "name": "STRZAŁ",
        "type": "shot",
        "instruction": "Strzał. Strzał trafia najbliższego Zombiaka na wybranym torze i zadaje mu 1 ranę. Dodatkowo, trafiony i nie zabity Zombiak cofa się o 1 pole, o ile jest to możliwe.",
        "description": "Strzał trafia najbliższego Zombiaka na wybranym torze i zadaje mu 1 ranę. Dodatkowo, trafiony i niezabity Zombiak cofa się o 1 pole, o ile jest to możliwe.",
        "flavor": "A ten zupełnie za nic!",
        "blockable": true,
        "race": "ludzie",
        "board": true,
    },
    {
        "id": 5,
        "amount": 1,
        "dmg": 4,
        "max_dmg": 4,
        "name": "ROPA",
        "type": "AOE",
        "instruction": "Zagraj Ropę na dowolne pole planszy, a następnie (opcjonalnie) wskaż kolejne sąsiadujące pola jej działania (nie po skosie). Ropa zadaje łącznie 4 rany na wskazane pola (rozdzielone według wyboru grającego ludźmi). Jeśli między traktowanymi Ropą Zombiakami jest puste pole, pochłania ono 1 punkt z siły rażenia Ropy.",
        "description": "Zagraj Ropę na dowolne pole i (opcjonalnie) wskaż kolejne pola jej działania (nie po skosie). Ropa zadaje łącznie 4 rany. Puste pole pochłania 1 punkt siły rażenia Ropy.",
        "flavor": "A teraz coś z rurociągu Przyjaźń",
        "race": "ludzie",
        "board": true,
    },
    {
        "id": 6,
        "amount": 1,
        "name": "DŁUGA SERIA",
        "dmg": 3,
        "piercing": true,
        "type": "shot",
        "instruction": "Seria. Długa seria trafia najbliższego Zombiaka na wybranym torze i zadaje mu 3 rany. Jeśli pierwsza lub druga rana zabiła Zombiaka, reszta pocisków z Serii trafia kolejnego Zombiaka stojącego na tym torze – i tak dalej. Dodatkowo, trafiony i nie zabity Zombiak cofa się o 1 pole, o ile jest to możliwe. Uwaga: Człowiek absorbuje wszystkie pociski wystrzelone w Serii.",
        "description": "Długa seria trafia najbliższego Zombiaka na torze i zadaje 3 rany. Jeśli pierwsza rana zabiła Zombniaka, drugą otrzymuje kolejny Zombiak na torze (itd.). Trafienie cofa Zombiaka o 1 pole. Człowiek absorbuje wszystkie pociski Serii.",
        "flavor": "Hasta la vista, baby!",
        "blockable": true,
        "race": "ludzie",
        "board": true,
    },
    {
        "id": 7,
        "amount": 1,
        "name": "RACA ŚWIETLNA",
        "type": "other",
        "instruction": "Weź maksymalnie 3 karty z wierzchu stosu kart Zombiaków (nie możesz wziąć ostatniej karty – Świt), wybierz z nich jedną i odrzuć na Śmietnik, a następnie odłóż pozostałe z powrotem w wybranej przez siebie kolejności. Dodatkowo, dołóż na V przecznicę tyle Zombiaków o sile 1, ile jest możliwe. Odrzucana karta jest widoczna dla graczy.",
        "description": "Weź maksymalnie 3 karty z wierzchu stosu kart Zombiaków (z wyjątkiem Świtu), odrzuć 1 z nich na Śmietnik, a pozostałe odłóż z powrotem w wybranej kolejności. Dodatkowo dołóż na V przecznicy tyle Zombiaków o sile 1 ile jest możliwe.",
        "flavor": "Zakazuje się używać rac na stadionie.",
        "race": "ludzie"
    },
    {
        "id": 8,
        "amount": 1,
        "name": "SIEĆ",
        "type": "AOE",
        "instruction": "Zagraj Sieć na dowolną liczbę Zombiaków sąsiadujących ze sobą (nie po skosie) o łącznej sile 6 lub mniej. Sieć uniemożliwia zasieciowanym Zombiakom jakikolwiek ruch (jednak zasieciowane Zombiaki mogą zostać zmasowane). Sieć przestaje działać na początku następnej tury ludzi.",
        "description": "Zagraj Sieć na sąsiadujące ze sobą Zombiaki (nie po skosie) o łącznej sile 6 lub mniej. Sieć unieruchamia Zombiaki aż do początku następnej tury ludzi.",
        "flavor": "Chyba trochę się zamotałeś.",
        "race": "ludzie",
        "board": true,
    },
    {
        "id": 9,
        "amount": 1,
        "name": "ULICA W OGNIU",
        "dmg": 1,
        "type": "AOE",
        "instruction": "Zagraj tę kartę na jeden dowolny tor oprócz środkowego. Każdy Zombiak na tym torze otrzymuje 1 ranę.",
        "description": "Zagraj tę kartę na jeden dowolny tor oprócz środkowego. Każdy Zombiak na tym torze otrzymuje 1 ranę.",
        "flavor": "I tak był do rozbiórki.",
        "race": "ludzie",
        "board": true,
    },
    {
        "id": 10,
        "amount": 3,
        "name": "STRZAŁ. TEN LEPSZY",
        "dmg": 2,
        "type": "shot",
        "blockable": true,
        "instruction": "Strzał. Strzał trafia najbliższego Zombiaka na wybranym torze i zadaje mu 2 rany. Dodatkowo, trafiony i nie zabity Zombiak cofa się o 1 pole, o ile jest to możliwe.",
        "description": "Strzał trafia najbliższego Zombiaka na wybranym torze i zadaje mu 2 rany. Dodatkowo trafiony i niezabity Zombiak cofa się o 1 pole, o ile jest to możliwe.",
        "flavor": "Prosto w tę zaropiałą gębę",
        "race": "ludzie",
        "board": true,
    },
    {
        "id": 11,
        "amount": 1,
        "name": "BECZKA",
        "type": "object",
        "instruction": "Wystaw Beczką na I przecznicy na dowolnym torze (na niezajętym polu). Beczka toczy się o 1 pole do przodu na początku tury ludzi. Kiedy znajdzie się na tym samym polu, co Zombiak, zabija go automatycznie i sama zostaje zniszczona (odrzuć ją na Śmietnik). Jeśli Zombiak wejdzie na pole, na którym znajduje się Beczka, ginie automatycznie, a Beczka zostaje odrzucona na Śmietnik. Beczka rozbija się o Mur i Auto (należy odrzucić ją na Śmietnik bez efektu), wpada do Dziury (i zapełnia ją - obie karty zostają odrzucają na Śmietnik), a także detonuje Minę.",
        "description": "Wystaw Beczkę na dowolnym polu pierwszej przecznicy. Co turę przesuń ją o 1 pole do przodu. Beczka zabija pierwszego na swojej drodze. Jeśli Zombiak wejdzie na Beczkę, ginie automatycznie. Beczka rozbija się o Mur i Auto, wpada do Dziury, a także detonuję Minę.",
        "flavor": "Wytoczę mocniejszy argument",
        "board": true,
        "race": "ludzie",
        'walkable': true
    },
    {
        "id": 12,
        "amount": 1,
        "name": "JAJNIK",
        "type": "other",
        "instruction": "Wybierz tor i wszystkie znajdujące się na nim Zombiaki (z wyjątkiem Psa i Kota) odwróć rewersem do góry - stają się oni Zombiakami o sile 1. Zagranie Jajnika wymaga wolnej linii strzału. Człowiek chroni przed działaniem Jajnika (jest odrzucany), ale tylko danego Zombiaka. Pozostałe Zombiaki na torze są normalnie zaatakowane w Zombiaki o sile 1. Jeśli Zombiak, którego zaatakował Jajnik posiada specjalną cechę (np. Kuloodporny czy Koń trojański), to po zamianie w Zombiaka o sile 1, traci tę cechę. Karty (z wyjątkiem Kota i Misia) czy żetony (ran, galarety) leżące na karcie Zombiaka są odrzucane, tym samym ich efekty przestają działać.",
        "description": "Wybierz tor i wszystkie znajdujące się na nim Zombiaki (z wyjątkiem Psa i Kota) stają się one Zombiakami o sile 1.",
        "flavor": "Bierz ich!",
        "blockable": true,
        "race": "ludzie",
        "board": true,
    },
    {
        "id": 13,
        "amount": 1,
        "name": "SNAJPER",
        "dmg": 2,
        "type": "other",
        "instruction": "Strzał Snajpera trafia dowolnego (niekoniecznie pierwszego na linii strzału) Zombiaka na planszy i zadaje mu 2 rany. Dodatkowo, trafiony i nie zabity Zombiak cofa się o 1 pole, o ile jest to możliwe.",
        "description": "Strzał Snajpera trafia dowolnego (niekoniecznie pierwszego na linii strzału) Zombiaka na planszy i zadaje mu 2 rany. Dodatkowo, trafiony i nie zabity Zombiak cofa się o 1 pole, o ile jest to możliwe.",
        "flavor": "Już go kiedyś sprzątnąłem...",
        "race": "ludzie",
        "board": true,
    },
    {
        "id": 14,
        "amount": 1,
        "name": "GAZ ROZWESELAJĄCY",
        "type": "other",
        "instruction": "Zagraj Gaz rozweselający na maksymalnie 2 wybrane przez siebie Zombiaki. Przesuń każdego z nich o 1 pole w dowolnym kierunku (do przodu, do tyłu, w bok, ale nie po skosie), o ile to możliwe.",
        "description": "Zagraj Gaz rozweselający na maksymalnie 2 wybrane przez siebie Zombiaki. Przesuń każdego z nich o 1 pole w dowolnym kierunku (nie po skosie), o ile to możliwe.",
        "flavor": "Hi, hi, he, he, ho ,ho!",
        "race": "ludzie",
        "board": true,
    },
    {
        "id": 15,
        "amount": 1,
        "name": "DZIURA",
        "type": "object",
        "instruction": "Wystaw Dziurę na dowolnym niezajętym polu planszy. Jeżeli na pole z Dziurą wejdzie Zombiak o sile 1 lub 2, zginie automatycznie, a Dziura zostaje zapełniona (odrzuć ją na Śmietnik). Zombiak o sile 3 lub większej przechodzi przez Dziurę bez szwanku (Dziura zostaje na planszy). Jeżeli na pole z Dziurą wejdzie Zombiak z Człowiekiem, karta Człowieka i Dziura są odrzucane na Śmietnik. Jeśli do Dziury wejdzie Syjamczyk albo ranny Koń trojański, to po tym jak zginie, normalnie zamienia się w Zombiaki o sile 1. Dziura jest odrzucana. Jeśli na Dziurze stoi Zombiak o większej sile, niż 2 i otrzyma ranę oraz ma się cofnąć, to się cofa (o ile to możliwe) zamiast wpada do Dziury. Jeśli nie może albo nie ma się gdzie cofać, to wtedy normalnie zapada do Dziury. Uwaga: Ikony mózgów na karcie Dziury nie oznaczają ilość zadawanych ran, ale maksymalną siłę Zombiaka, jaki wpada do dziury.",
        "description": "Wystaw Dziurę na wolnym polu. Gdy wejdzie w nią Zombiak o sile 1 lub 2, automatycznie ginie, a Dziura jest zapełniona (odrzuć ją na Śmietnik). Zombiak o sile 3 lub większej przechodzi przez Dziurę bez szwanku. Karta Człowieka zapełnia Dziurę automatycznie.",
        "flavor": "Zemsta polskich drogowców",
        "board": true,
        "walkable": true,
        "race": "ludzie"
    },
    {
        "id": 16,
        "amount": 2,
        "name": "KREW",
        "type": "other",
        "instruction": "Przesuń jednego dowolnego Zombiaka w bok na sąsiedni tor, o ile to możliwe.",
        "description": "PRzesuń jednego dowolnego Zombiaka w bok na sąsiedny tor, o ile jest możliwe.",
        "flavor": "A rh+. Moja ulubiona.",
        "race": "ludzie",
        "board": true
    },
    {
        "id": 17,
        "amount": 3,
        "name": "ZAPORA",
        "type": "object",
        "instruction": "Wystaw Zaporę na jednym z niezajętych pól na pierwszej przecznicy. Zapora uniemożliwia jakikolwiek ruch Zombiaków na tym torze. Zapora przestaje działać na początku następnej tury ludzi",
        "description": "Wystaw Zaporę na jednym z niezajętych pół na pierwszej przecznicy. Zapora uniemożliwia jakikolwiek ruch Zombiaków na tym torze. Zapora przestaje działać na początku następnej tury Ludzi.",
        "flavor": "Chodnik chwilowo nieczynny.",
        "board": true,
        "race": "ludzie"
    },
    {
        "id": 18,
        "amount": 1,
        "name": "MUR Z RUPIECI",
        "type": "object",
        "mur": true,
        "hp": 5,
        "instruction": " Mur. Wystaw Mur z rupieci na dowolne niezajęte pole, z wyjątkiem: 1) pól sąsiadujących lub stykających się po skosie z Zombiakiem, 2) przecznic znajdujących się za jakimkolwiek Zombiakiem, 3) przecznicy piątej. Mur pozostaje na planszy do końca gry, chyba że zostanie zniszczony (Granat, Kilof). Zombiak nie może wejść na pole z Murem, chyba że sumaryczna siła tego Zombiaka oraz wszystkich stykających się Zombiaków idących za nim na tym torze wyniesie 5 lub więcej. W analogiczny sposób Zombiak może zostać cofnięty na Mur. Ponadto, na pola za Murem nie działają karty Reflektora, Zapory ani Jajnika. Uwaga: Ikony mózgów na karcie Muru z rupieci nie oznaczają ilości zadawanych Ran, ale minimalną siłę Zombiaków (ciągu Zombiaków) potrzebną do wejścia na Mur z rupieci.",
        "description": "Wystaw Mur na wolne pole, z wyjątkiem: pól sąsiadujących (też po skosie) z Zombiakiem; przecznic znajdujących się za Zombiakiem; przecznicy V. Zombiak nie może wejść na Mur, chyba że suma jego siły io wszystkich Zombiaków idących za nim wyniesie 5 lub więcej. Na pola za Murem nie działa Reflektor, Zapora, ani Jajnik.",
        "flavor": "Panowie, objazd!",
        "board": true,
        "walkable": true,
        "race": "ludzie"
    },
    {
        "id": 19,
        "amount": 1,
        "name": "ZMIATAJ",
        "type": "other",
        "instruction": "Wybierz jedną z kart przeciwnika, leżących na Cmentarzu i odrzuć ją na Śmietnik.",
        "description": "Wybierz jedną z kart przeciwnika, leżących na Cmentarzu i odrzuć ją na Śmietnik.",
        "flavor": "Nie, tak się bawić nie będziemy.",
        "board": 'deck',
        "race": "ludzie"
    },
    {
        "id": 20,
        "amount": 1,
        "name": "REFLEKTOR",
        "type": "other",
        "instruction": "Cofnij równocześnie o 1 pole wszystkie Zombiaki na jednym wybranym torze, o ile to możliwe.",
        "description": "Covnij równocześnie o 1 pole wszystkie Zombiaki na jednym wybranym torze, o ile to możliwe.",
        "flavor": "Parę słów do mikrofonu...",
        "blockable": true,
        "race": "ludzie",
        "board": true,
    },
    {
        "id": 21,
        "amount": 1,
        "name": "WYNOCHA",
        "type": "AOE",
        "instruction": "Cofnij równocześnie o 1 pole wszystkie Zombiaki na planszy. Zombiak cofa się, o ile jest za nim wolne pole",
        "description": "Cofnij równocześnie o 1 pole wszystkie Zombiaki na planszy. Zombiak cofa się, o ile jest za nim wolne pole.",
        "flavor": "Martwym wstęp wzbroniony.",
        "race": "ludzie"
    },
    {
        "id": 22,
        "amount": 1,
        "name": "CHUCK",
        "type": "other",
        "instruction": "Odrzuć na Śmietnik wierzchnią kartę ze stosu kart Zombiaków. Nie można zagrać tej karty, jeśli w talii Zombiaków pozostała już tylko ostatnia karta (Świt). Odrzucana karta jest widoczna dla graczy.",
        "description": "Odrzuć na Śmietnik wierzchnią kartę ze stosu kart Zombiaków",
        "flavor": "Chuck it out!",
        "race": "ludzie"
    },
    {
        "id": 23,
        "amount": 1,
        "name": "CEGŁA",
        "type": "shot",
        "dmg": 1,
        "instruction": "Cegła trafia dowolnego (niekoniecznie pierwszego na linii strzału) Zombiaka na planszy zadając mu 1 ranę. Trafiony Zombiak nie cofa się.",
        "description": "Cegła trafia dowolnego (niekoniecznie pierwszego na linii strzału) Zombiaka na planszy i zadaje mu 1 ranę. Trafiony Zombiak nie cofa się.",
        "flavor": "Podaj cegłę",
        "race": "ludzie",
        "board": true,
    },
    {
        "id": 24,
        "amount": 1,
        "name": "MIOTACZ",
        "type": "other",
        "dmg": 5,
        "max_dmg": 5,
        "instruction": "Zagraj Miotacz na najbliższą przecznicę od strony ludzi, na której znajduje się jakikolwiek Zombiak. Miotacz zadaje na tej przecznicy łącznie 5 ran, rozdzielanych dowolnie przez ludzi (jeśli między traktowanymi Miotaczem Zombiakami jest puste pole, pochłania ono 1 punkt z siły rażenia Miotacza).",
        "description": "Zagraj Miotacz na najbliższą przecznicę, na której znajduje się jakikolwiek Zombiak. Miotacz zadaje łącznie 5 ran, rozdzielanych przez ludzi (puste pole pochłania 1 punkt siły rażenia Miotacza).",
        "flavor": "Palenie szkodzi zdrowiu.",
        "blockable": true,
        "board": true,
        "race": "ludzie"
    },
    {
        "id": 25,
        "amount": 1,
        "name": "MINA",
        "type": "object",
        "dmg": 2,
        "blow_dmg": 1,
        "activation": ['MIOTACZ', 'ULICA W OGNIU', 'ROPA', 'GRANAT', 'BECZKA', 'AUTO'],
        "instruction": "Wystaw Minę na dowolnym niezajętym polu planszy, z wyjątkiem pól znajdujących się bezpośrednio przed Zombiakiem. Jeżeli na pole z Miną wejdzie Zombiak, następuje wybuch. Zombiak znajdujący się na polu z Miną otrzymuje 2 rany, zaś odłamek razi sąsiednie pola (wybrane przez grającego ludźmi, nie po skosie), zadając 1 ranę. Minę detonuje także Beczka, ogień (Miotacz, Ulica w ogniu, Ropa) lub wybuch (Granat, wybuchające Auto).",
        "description": "Wystaw Minę na wolnym polu, ale nie bezpośrednio przed Zombiakiem. Jeżeli na Minę wejdzie Zombiak, otrzymuje on 2 rany, zaś odłamek razi wybrane sąsiednie pole zadając 1 ranę (nie po skosie). Minę detonuje także Miotacz, Ulica w ogniu, Ropa, Granat, Beczka i Auto.",
        "flavor": "Pamiątka po Szkopach",
        "board": true,
        "walkable": true,
        "race": "ludzie"

    },
    {
        "id": 26,
        "amount": 1,
        "name": "MUR",
        "type": "object",
        "mur": true,
        "hp": 6,
        "instruction": "Mur. Wystaw Mur na dowolne niezajęte pole, z wyjątkiem: 1) pól sąsiadujących lub stykających się po skosie z Zombiakiem, 2) przecznic znajdujących się za jakimkolwiek Zombiakiem, 3)  przecznicy piątej. Mur pozostaje na planszy do końca gry, chyba że zostanie zniszczony (Granat, Kilof). Zombiak nie może wejść na pole z Murem, chyba że sumaryczna siła tego Zombiaka oraz wszystkich stykających się Zombiaków idących za nim na tym torze wyniesie 6 lub więcej. W analogiczny sposób Zombiak może zostać cofnięty na Mur. Ponadto, na pola za Murem nie działają karty Reflektora, Zapory ani Jajnika. Uwaga: Ikony mózgów na karcie Muru nie oznaczają ilości zadawanych Ran, ale minimalną siłę Zombiaków (ciągu Zombiaków) potrzebną do wejścia na Mur.",
        "description": "Wystaw Mur na wolne pole, z wyjątkiem: pól sąsiadujących (też po skosie) z Zombiakiem; przecznic znajdujących się za Zombiakiem; przecznicy V. Zombiak nie może wejść na Mur, chyba że suma jego siły io wszystkich Zombiaków idących za nim wyniesie 6 lub więcej. Na pola za Murem nie działa Reflektor, Zapora, ani Jajnik.",
        "flavor": "Bez spychacza- zapomnij.",
        "board": true,
        "walkable": true,
        "race": "ludzie"
    },
    {
        "id": 27,
        "amount": 1,
        "name": "BETONOWE BUCIKI",
        'type': 'other',
        'dmg': 1,
        "instruction": "Zagraj Betonowe buciki na wybranego przez siebie Zombiaka. Za każdym razem, kiedy ten Zombiak się poruszy (w dowolnym kierunku, również do tyłu), otrzymuje 1 ranę. Przed Betonowymi bucikami w żaden sposób nie chroni Człowiek. Jeśli Zombiak z Betonowymi bucikami będzie miał już tylko 1 i wejdzie na Barykadę, to ginie i nie wygrywa gry, chyba że będzie to Syamczyk albo Koń trojański, który po śmierci zamienia się w Zombiaki o sile 1. Po tym jak Zombiak z bucikami zginie, obie karty odrzucane są na Śmietnik.",
        "description": "Zagraj Betonowe Buciki na wybranego przez siebie Zombiaka. Za każdym razem, kiedy Zombiak się poruszy (w dowolnym kierunku, również do tyłu), otrzymuję 1 ranę. Człowiek nie chroni w żaden sposób przed Betonowymi bucikami.",
        "flavor": "Na rzeźbę łydek idealne.",
        "race": "ludzie",
        "board": true,
    },
    {
        "id": 28,
        "amount": 1,
        "name": "GRANAT",
        'type': 'other',
        "instruction": "Zagraj Granat na dowolne pole planszy. Granat automatycznie niszczy wszystkie karty (i ewentualny żeton galarety) znajdujące się na tym polu. Przed Granatem nie chroni Człowiek.",
        "description": "Zagraj Granat na dowolne pole planszy. Granat automatycznie niszczy wszystkie karty znajdujące się na tym polu. Przed Granatem nie chroni Człowiek.",
        "flavor": "Wyrwij zawlęczkę i policz do trzech.",
        "race": "ludzie",
        "board": true,
    },
    {
        "id": 29,
        "amount": 1,
        "name": "AUTO",
        'type': "object",
        'dmg': 1,
        'blow_dmg': 1,
        'activation': ['STRZAŁ', 'STRZAŁ. TEN LEPSZY', 'SNAJPER', 'KRÓTKA SERIA', 'DŁUGA SERIA', 'MIOTACZ', 'ULICA W OGNIU', 'ROPA', 'GRANAT', 'MINA'],
        "instruction": "Wystaw Auto na wolnym polu planszy, przy czym zagranie auta wymaga wolnej linii strzału. Wystawione na planszy Auto można w dowolnej chwili zdetonować za pomocą strzału (Strzał, Snajper, jeden pocisk Serii), ognia (Miotacz, Ulica w ogniu, Ropa) lub wybuchu (Granat, odłamek Miny). Zdetonowane Auto zadaje jedną ranę na polu, na którym stało i jedną na każdym dookoła (nawet po skosie). Zombiaki mogą normalnie wchodzić na pole zajęte przez Auto. Jeśli na polu z Autem znajduje się także Zombiak, gracz grający Ludźmi wybiera czy trafia Zombiaka, czy Auto.",
        "description": "Wystaw Auto na dowolnym wolnym polu. Auto można zdetonować za pomocą Strzału, Snajpera, Serii, Miotacza, Ulicy w ogniu, Ropy, Granatu, odłamka Miny. Zdetonowane zadaje 1 ranę na swoim polu i 1 na każdym dookoła (nawet po skosie). Zombiaki mogą wchodzić na pole z Autem.",
        "flavor": "Trabant! Nie trzeba detonatora!",
        "board": true,
        "walkable": true,
        "race": "ludzie"
    }
];