export const cards_zombiaki_json = [
    {
        "id": 1,
        "amount": 1,
        "name": "MIŚ",
        "type": "overlay",
        "overlay_text": "ZAGRAJ MISIA",
        "instruction": "Połóż Misia na wybranego Zombiaka (z wyjątkiem Psa i Kota). <br> Miś porusza się razem z Zombiakiem, na którym został położony. <br> Dopóki Miś żyje, to w twojej turze możesz zmniejszyć jego siłę o 1 (również, jeśli miałoby go to zabić), aby grający ludźmi odrzucił 2 karty, a nie 1 w najbliższej fazie Odrzucania. <br> Po zabiciu Misia, należy jego kartę odrzucić na Śmietnik. <br> Miś może być atakowany kartami z talii ludzi tak samo jak Zombiak. <br> Grający ludźmi, atakując, wybiera czy trafia Misia, czy Zombiaka. <br> Jeśli grający ludźmi rani Misia, to w ten sposób nie zwiększa ilości kart, jakie będzie musiał odrzucać. <br> Jeśli grający ludźmi zada Misiowi więcej ran niż potrzeba do jego zabicia, to pozostałe rany otrzymuje Zombiak, na którym Miś był położony. <br> Trafiony i niezabity Miś się nie cofa (tylko Zombiak się cofają). <br> Jeśli zginie Zombiak, który miał Misia, to Miś ginie, bez względu na to, ile miał jeszcze siły. <br> Chyba że Misia miał Syjamczyk, Koń trojański albo Zombiak zaatakowany przez Jajnika – w takiej sytuacji Miś pozostaje na nowo powstałym Zombiaku o sile 1. <br> Na Misia nie można zagrywać kart z talii zombiaków.",
        "description": "Połóż Misia na wybranego Zombiaka (z wyjątkiem Psa i Kota). Miś porusza się razem z Zombiakiem. W twojej turze możesz zmniejszyć siłę Misia o 1, aby grający ludźmi odrzucił 2 karty, a nie 1 w najbliższej fazie Odrzucenia. Miś może być atakowany tak jak Zombiak. Grający ludźmi może atakować Zombiaka lub Misia - jeśli Miś otrzyma więcej ran niż ma aktualnie siły, to pozostałe rany otrzymuje Zombiak. Jeśli Zombiak zginie, to Miś ginie razem z nim.",
        "flavor": "Misio chce zombiaczka.",
        "hp": 4,
        "max_hp": 4,
        "special": true,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 2,
        "amount": 2,
        "name": "KLIK",
        "type": "other",
        "description": "Możesz zagrać Klik w turze Ludzi jako odpowiedź na Strzał, Serię lub Snajpera. Klik niweluje działanie jednej takiej karty.",
        "flavor": "Johnowi Rambo się to nie zdarzało.",
        "special": true,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 3,
        "amount": 1,
        "name": "WACEK",
        "type": "zombiak",
        "description": "Na początku twojej tury Zombiak przesuwa się o 1 pole do przodu.",
        "flavor": "Taki sobie, na trzy plus.",
        "hp": 3,
        "max_hp": 3,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 4,
        "amount": 1,
        "name": "KOT",
        "type": "zombiak",
        "instruction": "Wystaw Kota zgodnie z regułami wystawiania Zombiaków. <br> Kot porusza się przed Zombiakami i może poruszać się o 1 lub 2 pola. <br> Kierunek ruchu jest dowolny, z wyjątkiem ruchu po skosie (może poruszyć się w bok, nawet gdy ruch na torze, na którym się znajduje jest zablokowany przez kartę blokująca ruch na tym torze). <br> Kot może wejść na pole zajęte przez innego Zombiaka i odwrotnie. <br> Jeśli Kot i inny Zombiak będą zajmować jedno pole, kot pierwszy otrzymuje obrażenia. <br> Trafiony i niezabity Kot nie cofa się. <br> Jeśli następnie grający ludźmi zada Kotu więcej ran niż potrzeba do jego zabicia, to pozostałe rany otrzymuje Zombiak stojący na polu z Kotem. <br> Wszystkie zasady wpływające na Zombiaki dotyczą także Kota. <br> Po dotarciu Kota do barykady ludzi nie się nie dzieje (Kot nie wygrywa gry). <br> Na Kota nie można zagrywać kart z talii zombiaków.",
        "description": "Kot porusza się przed Zombiakami o 1 lub 2 pola w dowolnym kierunku (nie po skosie). Może wejść na pole zajęte przez innego Zombiaka i odwrotnie. Jeśli Kot i Zombiak będą na jednym polu, to Kot pierwszy otrzymuje obrażenia. Trafiony i niezabity Kot nie cofa się. Jeśli Kot otrzyma więcej ran niż potrzeba do jego zabicia, to pozostałe rany otrzymuje Zombiak na tym samym polu. Po dotarciu Kota do Barykady ludzi nic się nie dzieje. Na Kota nie można zagrywać kart z talii zombich.",
        "flavor": "Wlazł kotek na grobek",
        "hp": 2,
        "max_hp": 2,
        "special": true,
        "race": "zombiaki",
        "pet": true,
        "pet_move": 2,
        "board": true
    },
    {
        "id": 5,
        "amount": 1,
        "name": "KRYSTYNKA",
        "type": "zombiak",
        "instruction": "Na początku twojej tury przesuń Zombiaka o 1 pole do przodu. <br> Jeśli w tej samej przecznicy co ona znajduje się inny Zombiak, to nie wolno zagrywać przeciwko niej Strzałów, Serii, Snajpera, Miotacza, Cegły. <br> Jeśli zagrywasz Miotacz na przecznicę, w której znajduje się Krystynka, zabijając najpierw inne Zombiaki, to pozostałe rany (jeśli jeszcze takie będą), możesz przydzielić Krystynce. <br> Przykład: w przecznicy stoją od lewej: Zombiak o sile 2, Zombiak o sile 1 i Krystynka. Używając Miotacza, zadajesz 2 rany pierwszemu i 1 ranę drugiemu Zombiakowi, dzięki czemu ich zabijasz – i pozostałe 2 rany możesz przydzielić Krystynce.",
        "description": "Na początku twojej tury przesuń Zombiaka o 1 pole do przodu. Dodatkowo, jeśli w tej samej przecznicy co ona znajduje się inny Zombiak, to nie wolno zagrywać przeciwko niej: Strzałów, Serii, Snajpera, Miotacza, Cegły.",
        "flavor": "Silikon nie gnije.",
        "hp": 3,
        "max_hp": 3,
        "special": true,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 6,
        "amount": 1,
        "name": "ZENEK",
        "type": "zombiak",
        "description": "Na początku twojej tury Zombiak przesuwa się o 1 pole do przodu.",
        "flavor": "Za życia też go nikt nie lubił.",
        "hp": 3,
        "max_hp": 3,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 7,
        "amount": 1,
        "name": "ANDRZEJ",
        "type": "zombiak",
        "description": "Na początku twojej tury Zombiak przesuwa się o 1 pole do przodu.",
        "flavor": "Powróżyć Ci?",
        "hp": 3,
        "max_hp": 3,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 8,
        "amount": 1,
        "name": "KILOF",
        "type": "other",
        "instruction": "Odrzuć na Śmietnik dowolną leżącą na planszy kartę planszy z talii Ludzi (z wyjątkiem Dziury). <br> Można również odrzucić kartę leżącą pod Zombiakiem, np. gdy Zombiak stoi na Murze.",
        "description": "Odrzuć na Śmietnik dowolną, leżącą na planszy kartę planszy z talii ludzi (z wyjątkiem Dziury).",
        "flavor": "Niestety to mi przeszkadza.",
        "special": true,
        "race": "zombiaki",
        'board': true,
    },
    {
        "id": 9,
        "amount": 3,
        "name": "CZŁOWIEK",
        "type": "overlay",
        'instruction': "Połóż Człowieka na dowolnym Zombiaku (z wyjątkiem Psa i Kota) znajdującym się na planszy. <br> Człowiek porusza się razem z Zombiakiem, na którym został położony i absorbuje wszystkie obrażenia wynikające z jednej karty zadane temu Zombiakowi (nawet z Beczki), po czym ginie (jego karta jest odrzucana). <br> Jeden Zombiak może zasłaniać się jednocześnie tylko jednym Człowiekiem. <br> Człowiek chronι przed działaniem Jajnika, ale tylko danego Zombiaka. <br> Człowiek w żaden sposób nie chroni przed działaniem Betonowych bucików.",
        "description": "Połóż Człowieka na dowolnym Zombiaku. Człowiek absorbuje wszystkie obrażenia wynikające z jednej karty zadane temu Zombiakowi, po czym ginie.",
        "flavor": "Do kumpla będziesz strzelał?",
        "special": true,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 10,
        "amount": 1,
        "name": "WIADRO",
        "type": "other",
        "instruction": "Nie możesz odrzucić tej karty w fazie Odrzucenia. <br> Musisz ją zagrać jako pierwszą zagraną kartę w turze, w której ją dociągnąłeś - wybierz dowolnego Zombiaka (z wyjątkiem Psa i Kota) i porusz go o 1 pole do tyłu. <br> Jeśli żaden Zombiak nie jest w stanie poruszać się do tyłu, to wybierz Zombiaka i zadaj mu 1 ranę. <br> Jeśli pociągnąłeś Wiadro, a na planszy nie ma żadnego Zombiaka (np. w pierwszej turze), to i tak musisz je zagrać, ale nie ma ono żadnego efektu.",
        "description": "Nie możesz tej karty odrzucić. Musisz ją zagrać jako pierwszą kartę w turze, w której ją dociągnąłeś – wybierz dowolnego Zombiaka i porusz go o 1 pole do tyłu. Jeśli żaden Zombiak nie jest w stanie poruszyć się do tyłu, to wybrany przez ciebie Zombiak otrzymuje 1 ranę.",
        "flavor": "Hełm z ograniczoną widocznością.",
        "special": true,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 11,
        "amount": 1,
        "name": "STEFAN",
        "type": "zombiak",
        "description": "Na początku twojej tury Zombiak przesuwa się o 1 pole do przodu.",
        "flavor": "Kwiaty we włosach potargał wiatr...",
        "hp": 4,
        "max_hp": 4,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 12,
        "amount": 1,
        "name": "MARIUSZ",
        "type": "zombiak",
        "description": "Na początku twojej tury Zombiak przesuwa się o 1 pole do przodu.",
        "flavor": "Wszystkie Mariusze to fajne chłopaki",
        "hp": 4,
        "max_hp": 4,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 13,
        "amount": 2,
        "name": "TERROR",
        "type": "other",
        "description": "Grający ludźmi w następnej turze może zagrać tylko jedną kartę",
        "flavor": "Ty! W garniturku! Skądżeś się tu wziął?",
        "special": true,
        "race": "zombiaki"
    },
    {
        "id": 14,
        "amount": 1,
        "name": "PIES",
        "type": "zombiak",
        "instruction": " Wystaw Psa zgodnie z regulami wystawiania Zombiaków. <br> Pies porusza się przed Zombiakami i może poruszyć się od 1 do 3 pól. <br> Kierunek ruchu jest dowolny, z wyjątkiem ruchu po skosie (może poruszać się w bok, nawet gdy ruch na torze, na którym się znajduje jest zablokowany przez kartę blokującą ruch na tym torze). <br> Wszystkie zasady wpływające na Zombiaki dotyczą także Psa. <br> Po dotarciu Psa do barykady ludzi nie się nie dzieje (Pies nie wygrywa gry). Na Psa nie można zagrywać kart z talii zombiaków.",
        "description": "Pies porusza się przed Zombiakami od 1 do 3 pól w dowolnym kierunku (nie po skosie). Po dotarciu Psa do Barykady ludzi nic się nie dzieje. Na Psa nie można zagrywać kart z talii zombich.",
        "flavor": "Najlepszy przyjaciel Zombiaka.",
        "hp": 1,
        "max_hp": 1,
        "special": true,
        "race": "zombiaki",
        "pet": true,
        "pet_move": 3,
        "board": true
    },
    {
        "id": 15,
        "amount": 1,
        "name": "MŁODY",
        "type": "zombiak",
        "instruction": "Na początku twojej tury przesuń Zombiaka o 1 pole do przodu. <br> Siła Młodego jest tym większa, im bliżej Barykady się on znajduje, tzn. podstawowo jego siła wynosi 2, na IV przecznicy - 3, na III przecznicy - 4, na II przecznicy - 5, na I przecznicy - 6. <br> Jeśli Młody zostanie masowany z innym Zombiakiem, to jego wkład w siłę nowego Zombiaka wynosi tylko 2, bez względu na przecznicę na której się znajduje.",
        "description": "Na początku twojej tury przesuń Zombiaka o 1 pole do przodu. Siła Młodego jest tym większa, im bliżej Barykady się znajduje. Siła 2 (podstawowo), Siła 3 (na IV przecznicy), Siła 4 (na III przecznicy), Siła 5 (na II przecznicy), Siła 6 (na I przecznicy).",
        "flavor": "Jaki Zombiak, taki syn.",
        "hp": 2,
        "max_hp": 2,
        "special": true,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 16,
        "amount": 1,
        "name": "PAZURY",
        "type": "overlay",
        "instruction": "Zagraj Pazury na wybranego Zombiaka (z wyjątkiem Psa i Kota).<br> Pazury zwiększają siłę Zombiaka o 1.",
        "description": "ZAgraj Pazury na wybranego Zombiaka. Pazury zwiększają siłę Zombiaka o 1.",
        "flavor": "Może małe manicure?",
        "special": true,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 17,
        "amount": 1,
        "name": "KAZIMIERZ",
        "type": "zombiak",
        "description": "Na początku twojej tury Zombiak przesuwa się o 1 pole do przodu.",
        "flavor": "Atrakcyjny to on nie jest.",
        "hp": 3,
        "max_hp": 3,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 18,
        "amount": 1,
        "name": "KRZYSZTOF",
        "type": "zombiak",
        "description": "Na początku twojej tury Zombiak przesuwa się o 1 pole do przodu.",
        "flavor": "Mięso armatnie. Raczej tatar niż schabowe.",
        "hp": 2,
        "max_hp": 2,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 19,
        "amount": 1,
        "name": "BOSS",
        "type": "overlay",
        "overlay_text": "ZAGRAJ BOSSA",
        'instruction': 'Połóż Bossa na dowolnym Zombiaku (z wyjątkiem Psa i Kota) znajdującym się na planszy. <br> Boss porusza się razem z Zombiakiem, na którym został położony. <br> Boss może wydać 3 rozkazy (1 na turę, również w turze, w której został zagrany) dotyczące ruchu innego Zombiaka (z wyjątkiem Psa i Kota). <br> Może nakazać dodatkowo ruch: do przodu, do tyłu lub w bok. <br> Rozkazów słuchają tylko Zombiak o sile mniejszej bądź równej 3. <br> Jeżeli Zombiak-Boss zginie, wszystkie Zombiaki cofają się o jedną przecznicę jeśli to możliwe. <br> Boss nie może wydać rozkazu Zombiakowi, który znajduje się na torze, na którym ruch jest zablokowany. <br> Jeśli Bossem jest Syjamczyk lub Koń trojański i zginie, to najpierw należy rozpatrzyć efekt śmierci Syjamczyka/ Konia trojańskiego, a dopiero potem śmierci Bossa(odrzucenie karty Bossa i cofanie się Zombiaków). <br> Jeśli Zombiak - Boss nie ginie, ale jest zmieniany w Zombiaka o sile 1(np.w wyniku działania Jajnika), to karta Bossa jest odrzucana, a Zombiaki na planszy nie cofają się.',
        "description": "Połóż Bossa na dowolnym Zombiaku. Boss może wydać 3 rozkazy (1 na turę) pozwalające na dodatkowy ruch innego Zombiaka. Rozkazów słuchają Zombiaki o sile 3 i mniejszej. Gdy Zombiak-Boss zginie, wszystkie Zombiaki cofają się o 1 pole.",
        "flavor": "Teraz ja tu rządzę.",
        "special": true,
        'hp': 3,
        'max_hp': 3,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 20,
        "amount": 1,
        "name": "MARIAN",
        "type": "zombiak",
        "description": "Na początku twojej tury Zombiak przesuwa się o 1 pole do przodu.",
        "flavor": "Marian zaprasza do tańca.",
        "hp": 4,
        "max_hp": 4,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 21,
        "amount": 1,
        "name": "CZESIEK",
        "type": "zombiak",
        "description": "Na początku twojej tury Zombiak przesuwa się o 1 pole do przodu.",
        "flavor": "Taki mały władca much.",
        "hp": 2,
        "max_hp": 2,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 22,
        "amount": 1,
        "name": "SYJAMCZYK",
        "type": "zombiak",
        "instruction": "Na początku twojej tury przesuń Zombiaka o 1 pole do przodu. <br> Dodatkowo, kiedy Syjamczyk zostanie zabity, zamienia się w 2 Zombiaki o sile 1. <br> Jeśli nie ma wystarczającej liczby wolnych pól na planszy, to Zombiaków pojawi się odpowiednio mniej. <br> Jeśli zginie Syjamczyk, który jest dodatkowo Bossem, to najpierw należy rozpatrzyć efekt śmierci Syjamczyka, a dopiero potem śmierci Bossa (odrzucenie karty Bossa i cofające się Zombiaki).",
        "description": "Na początku twojej tury przesuń Zombiaka o 1 pole do przodu. Dodatkowo, kiedy Syjamczyk zginie, zamienia się w 2 Zombiaki o sile 1 (odwróć jego kartę w miejscu, w którym zginął, a drugą połóż na wolnym polu sąsiadującym z nim z boku lub z tyłu).",
        "flavor": "Co dwie głowy, to nie jedna.",
        "hp": 2,
        "max_hp": 2,
        "special": true,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 23,
        "amount": 1,
        "name": "GALARETA",
        "type": "zombiak",
        "instruction": "Na początku twojej tury przesuń Zombiaka o 1 pole do przodu. <br> Kiedy Galareta zostanie zabity, połóż w jego miejscu żeton galarety. <br> Pierwszy Zombiak (z wyjątkiem Psa i Kota), który wejdzie na pole z tym żetonem, zabiera go (połóż żeton na karcie tego Zombiaka) i zwiększa on jego siłę o 2. <br> Jeśli żeton galarety zbierze Zombiak z Misiem, to galareta zwiększa siłę Zombiaka, a nie Misia. <br> Żeton galarety nie zajmuje pola na planszy, więc w tym samym miejscu może być wystawione np. Auto czy Mur.",
        "description": "Na początku twojej tury przesuń Zombiaka o 1 pole do przodu. Dodatkowo, kiedy Galareta zostanie zabity, pozostawia w swoim miejscu żeton galarety. Pierwszy Zombiak (z wyjątkiem Psa i Kota), który wejdzie na pole z tym żetonem, zabiera go – dodaje mu on +2 siły.",
        "flavor": "Żelatyna jest dobra na kości.",
        "hp": 3,
        "max_hp": 3,
        "special": true,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 24,
        "amount": 1,
        "name": "GŁÓD",
        "type": "other",
        "instruction": "Przesuń dowolnego Zombiaka (z wyjątkiem Psa i Kota) o 1 pole do przodu, o ile jest to możliwe.",
        "description": "Przesuń dowolnego Zombiaka o 1 pole do przodu o ile jest to możliwe",
        "flavor": "Bierz go!",
        "special": true,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 25,
        "amount": 1,
        "name": "ARKADIUSZ",
        "type": "zombiak",
        "description": "Na początku twojej tury Zombiak przesuwa się o 1 pole do przodu.",
        "flavor": "Jak się bawiłeś na mojej stypie?",
        "hp": 3,
        "max_hp": 3,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 26,
        "amount": 1,
        "name": "MIETEK",
        "type": "zombiak",
        "description": "Na początku twojej tury Zombiak przesuwa się o 1 pole do przodu.",
        "flavor": "Setka na wzmocnienie Mietka.",
        "hp": 3,
        "max_hp": 3,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 27,
        "amount": 2,
        "name": "MASA",
        "type": "other",
        "instruction": "Przesuń dowolnego Zombiaka (z wyjątkiem Psa lub Kota) na sąsiednie pole (do przodu, do tyłu lub w bok) zajmowane przez innego Zombiaka. <br> Obie karty Zombiaków traktowane są jako nowy Zombiak o sile równej sumie ich sił. <br> Możesz masować Zombiak, które znajdują się pod działaniem Sieci, ale tylko jeśli oba są pod sięcią. <br> Jeśli za pomocą karty Masa łączone są dwa Zombiaki, z których każdy posiada Człowieka, po zmasowaniu pozostaje tylko jeden Człowiek. <br> Jeśli łączone są dwa Zombiaki z których przynajmniej jeden posiada cechę specjalną, (np. Kuloodporny czy Koń trojański), to nowy Zombiak traci te cechy i liczy się tylko jego siła.",
        "description": "Przesuń dowolnego Zombiaka na sąsiednie pole zajmowane przez innego Zombiaka (również jeśli obaj są zasieciowani). Obaj traktowani są jak nowy Zombiak o sile równej sumie ich sił. Jeśli zmasujesz Zombiaka z cechą specjalną, to przestaje ona obowiązywać.",
        "flavor": "Kupy nikt nie rusza.",
        "special": true,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 28,
        "amount": 1,
        "name": "MIĘSO",
        "type": "other",
        "description": "Wybierz jedną z kart przeciwnika leżących na Barykadzie i odrzuć ją na Śmietnik",
        "flavor": "Łap pan teściową!",
        "special": true,
        "board": 'deck',
        "race": "zombiaki"
    },
    {
        "id": 29,
        "amount": 1,
        "name": "PAPU",
        "type": "other",
        "instruction": "Usuń do  znaczników ran z wybranego Zombiaka (z wyjątkiem Psa i Kota). <br> Nie możesz zagrać tej karty na Misia, bo Miś nie jest Zombiakiem.",
        "description": "Usuń do 2 znaczników ran z wybranego Zombiaka.",
        "flavor": "Dietę zaczynam od jutra.",
        "special": true,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 30,
        "amount": 1,
        "name": "KOŃ TROJAŃSKI",
        "type": "zombiak",
        "instruction": "Na początku twojej tury przesuń Zombiaka o 1 pole do przodu. <br> Dodatkowo, kiedy Koń trojański zostanie zabity, zamienia się w 3 Zombiaki o sile 1. <br> Jeśli nie ma wolnych pól na planszy, to Zombiaków pojawi się odpowiednio mniej. <br> Jeśli zginie Koń trojański, który jest dodatkowo Bossem, to najpierw należy rozpatrzyć efekt śmierci Konia trojańskiego, a dopiero potem śmierci Bossa (odrzucenie karty Bossa i cofające się Zombiaki).",
        "description": "Na początku twojej tury przesuń Zombiaka o 1 pole do przodu. Dodatkowo, kiedy Koń Trojański zginie, zamienia się w 3 Zombiaki o sile 1 (odwróć jego kartę w miejscu, w którym zginął, a pozostałe 2 połóż na wolnych polach sąsiadujących z nim z boku i/lub z tyłu).",
        "flavor": "Zwykła zabawka, zwykła zabawka...",
        "hp": 2,
        "max_hp": 2,
        "special": true,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 31,
        "amount": 1,
        "name": "SPADAJ",
        "type": "other",
        "description": "Zamień miejscami dwa Zombiaki sąsiadujące ze sobą (nie po skosie), o ile żaden z nich nie jest splątany siecią. Karta nie działa na Psa ani Kota.",
        "flavor": "Miejsce dla mądrzejszego!",
        "special": true,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 32,
        "amount": 1,
        "name": "UGRYZIENIE",
        "type": "other",
        "instruction": "Zagraj Ugryzienie na Człowieka leżącego na karcie Zombiaka. <br> Ugryzienie zamienia Człowieka w nowego Zombiaka o sile 1 (z tyłu lub z boku). <br> Jeśli wszystkie sąsiednie pola są zablokowane, Ugryzienie nie może zostać zagrane.",
        "description": "Zamień Człowieka w nowego Zombiaka o sile 1, umieść go na sąsiednim polu (z tyłu lub z boku). Jeżeli wszystkie sąsiednie pola są zablokowane, Ugryzienie nie może zostać zagrane.",
        "flavor": "Pajęczyca.",
        "special": true,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 33,
        "amount": 1,
        "name": "IWAN",
        "type": "zombiak",
        "description": "Na początku twojej tury Zombiak przesuwa się o 1 pole do przodu.",
        "flavor": "IWAN: chłopak na piątkę.",
        "hp": 5,
        "max_hp": 5,
        "race": "zombiaki",
        "board": true
    },
    {
        "id": 34,
        "amount": 1,
        "name": "KULOODPORNY",
        "type": "zombiak",
        "description": "Na początku twojej tury przesuń Zombiaka o 1 pole do przodu. Dodatkowo, Kuloodporny ignoruje całkowicie efekty Strzałów.",
        "flavor": "Twardy jak dębowa trumna.",
        "hp": 3,
        "max_hp": 3,
        "special": true,
        "race": "zombiaki",
        "board": true
    }
];

export const zombiak_masa = {
    "id": "masa",
    "name": "MASA",
    "type": "zombiak",
    "description": "Na w kupie siła w tury Zombiak przesuwa się o 1 pole do przodu.",
    "flavor": "W kupię siła.",
    "hp": 0,
    "max_hp": 0,
    "race": "zombiaki",
    "board": true
}
export const zombiak_1 = {
    'id': 'rewers',
    'name': "REWERS",
    "description": "Na w kupie siła w tury Zombiak przesuwa się o 1 pole do przodu.",
    'race': 'zombiaki',
    'type': 'zombiak',
    'hp': 1,
    'max_hp': 1,
    "board": true
}

export const galareta_overlay = {
    'id': 'galareta',
    'name': 'GALARETA',
    'type': 'overlay',
    'description': 'Dodatkowe 2 punkty życia',
    'flavor': 'Żelatyna to samo żdrowie',
    'race': 'zombiaki'
}